version: 2.1

executors:
  python-27:
    docker:
        - image: circleci/python:2.7-stretch-browsers
    resource_class: large
  python-36:
    docker:
        - image: circleci/python:3.6-stretch-browsers
    resource_class: large


jobs:
  "python-2.7": &test-template
    executor: python-27

    steps:
      - checkout

      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "dev-requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install dependencies
          command: |
            sudo pip install virtualenv
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "dev-requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
          paths:
          - "venv"

      - run:
          name: Flake8
          command: |
            . venv/bin/activate
            flake8 dash_auth setup.py

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest -v tests.test_basic_auth_integration
            python -m unittest -v tests.test_plotly_auth_integration
            python -m unittest -v tests.test_api_requests
            python -m unittest -v tests.test_plotlyauth

  "python-3.6":
    <<: *test-template
    executor: python-36

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"