name: Generate release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yml # Build the package artifacts
    with:
      python-version: '3.10'
      node-version: 'v18.16.0'

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download Python distributions
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist/
      - name: Upload GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl,dist/*.tar.gz,npm-dist/*.tgz"
          draft: true